// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/br4tech/auth-nex/internal/infra/delivery"
	"github.com/br4tech/auth-nex/internal/infra/repository"
	"github.com/br4tech/auth-nex/internal/usecase/auth"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAuthHandler(db *gorm.DB) *handler.AuthHandler {
	iAuthRepository := repository.NewAuthRepository(db)
	iAuthUseCase := usecase.NewAuthUseCase(iAuthRepository)
	authHandler := handler.NewAuthHandler(iAuthUseCase)
	return authHandler
}
