// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	domain "github.com/br4tech/auth-nex/internal/core/domain"
	dto "github.com/br4tech/auth-nex/internal/dto"
	model "github.com/br4tech/auth-nex/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIUserUseCase is a mock of IUserUseCase interface.
type MockIUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIUserUseCaseMockRecorder
}

// MockIUserUseCaseMockRecorder is the mock recorder for MockIUserUseCase.
type MockIUserUseCaseMockRecorder struct {
	mock *MockIUserUseCase
}

// NewMockIUserUseCase creates a new mock instance.
func NewMockIUserUseCase(ctrl *gomock.Controller) *MockIUserUseCase {
	mock := &MockIUserUseCase{ctrl: ctrl}
	mock.recorder = &MockIUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserUseCase) EXPECT() *MockIUserUseCaseMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockIUserUseCase) Authenticate(userReq *dto.UserTokenDTO) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", userReq)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockIUserUseCaseMockRecorder) Authenticate(userReq interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockIUserUseCase)(nil).Authenticate), userReq)
}

// Create mocks base method.
func (m *MockIUserUseCase) Create(user *domain.User) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIUserUseCaseMockRecorder) Create(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUserUseCase)(nil).Create), user)
}

// ValidateAccessToken mocks base method.
func (m *MockIUserUseCase) ValidateAccessToken(tokenString string) (*model.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", tokenString)
	ret0, _ := ret[0].(*model.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockIUserUseCaseMockRecorder) ValidateAccessToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockIUserUseCase)(nil).ValidateAccessToken), tokenString)
}

// MockIPermissionUseCase is a mock of IPermissionUseCase interface.
type MockIPermissionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIPermissionUseCaseMockRecorder
}

// MockIPermissionUseCaseMockRecorder is the mock recorder for MockIPermissionUseCase.
type MockIPermissionUseCaseMockRecorder struct {
	mock *MockIPermissionUseCase
}

// NewMockIPermissionUseCase creates a new mock instance.
func NewMockIPermissionUseCase(ctrl *gomock.Controller) *MockIPermissionUseCase {
	mock := &MockIPermissionUseCase{ctrl: ctrl}
	mock.recorder = &MockIPermissionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPermissionUseCase) EXPECT() *MockIPermissionUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIPermissionUseCase) Create(name string) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIPermissionUseCaseMockRecorder) Create(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPermissionUseCase)(nil).Create), name)
}

// FindByName mocks base method.
func (m *MockIPermissionUseCase) FindByName(name string) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", name)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockIPermissionUseCaseMockRecorder) FindByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockIPermissionUseCase)(nil).FindByName), name)
}

// MockICompanyUseCase is a mock of ICompanyUseCase interface.
type MockICompanyUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockICompanyUseCaseMockRecorder
}

// MockICompanyUseCaseMockRecorder is the mock recorder for MockICompanyUseCase.
type MockICompanyUseCaseMockRecorder struct {
	mock *MockICompanyUseCase
}

// NewMockICompanyUseCase creates a new mock instance.
func NewMockICompanyUseCase(ctrl *gomock.Controller) *MockICompanyUseCase {
	mock := &MockICompanyUseCase{ctrl: ctrl}
	mock.recorder = &MockICompanyUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICompanyUseCase) EXPECT() *MockICompanyUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockICompanyUseCase) Create(company *domain.Company) (*domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", company)
	ret0, _ := ret[0].(*domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockICompanyUseCaseMockRecorder) Create(company interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICompanyUseCase)(nil).Create), company)
}

// FindById mocks base method.
func (m *MockICompanyUseCase) FindById(id int) (*domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", id)
	ret0, _ := ret[0].(*domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockICompanyUseCaseMockRecorder) FindById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockICompanyUseCase)(nil).FindById), id)
}

// MockITenantUseCase is a mock of ITenantUseCase interface.
type MockITenantUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockITenantUseCaseMockRecorder
}

// MockITenantUseCaseMockRecorder is the mock recorder for MockITenantUseCase.
type MockITenantUseCaseMockRecorder struct {
	mock *MockITenantUseCase
}

// NewMockITenantUseCase creates a new mock instance.
func NewMockITenantUseCase(ctrl *gomock.Controller) *MockITenantUseCase {
	mock := &MockITenantUseCase{ctrl: ctrl}
	mock.recorder = &MockITenantUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITenantUseCase) EXPECT() *MockITenantUseCaseMockRecorder {
	return m.recorder
}

// CreateTenantWithCompanyAndAdmin mocks base method.
func (m *MockITenantUseCase) CreateTenantWithCompanyAndAdmin(tenant *dto.TenantDTO) (*domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenantWithCompanyAndAdmin", tenant)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenantWithCompanyAndAdmin indicates an expected call of CreateTenantWithCompanyAndAdmin.
func (mr *MockITenantUseCaseMockRecorder) CreateTenantWithCompanyAndAdmin(tenant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenantWithCompanyAndAdmin", reflect.TypeOf((*MockITenantUseCase)(nil).CreateTenantWithCompanyAndAdmin), tenant)
}
